<script setup lang="ts">
// T5.4 (SPEC.md §4.6): the page exists; CHANGELOG.md is generated by Changesets and rendered here in T11.3 (REQ-062 AC2).
import { useSeoMeta } from 'nuxt/app'

useSeoMeta({ title: 'Changelog' })
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-bold text-highlighted">Changelog</h1>
    <PendingNotice task="T11.3" />
  </div>
</template>
